apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
      - name: container-name
        image: registry.dev.svc.cluster.local:5000/nginx:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
